package com.uds.horbac.core.dao.emp_famillyInfo;

import com.uds.horbac.core.entities.emp_famillyInfo.PartenaireConjugal;
import io.swagger.annotations.Api;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Api(tags = "PartenaireConjugal Entity")
@RepositoryRestResource(path = "partenaireConjugals", exported = true)
public interface PartenaireConjugalRepository extends JpaRepository<PartenaireConjugal, Long> {

}
