package com.uds.horbac.core.dao.emp_personalInfo;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import com.uds.horbac.core.entities.emp_personalInfo.Handicap;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Repository
public interface HandicapRepository extends JpaRepository<Handicap, Long>, JpaSpecificationExecutor<Handicap>{

}
