package com.uds.horbac.core.dao.emp_personalInfo;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import com.uds.horbac.core.entities.emp_personalInfo.Handicap;

import io.swagger.annotations.Api;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Api(tags = "Handicap Entity")
@RepositoryRestResource(path = "handicaps", exported = true)
public interface HandicapRepository extends JpaRepository<Handicap, Long>, JpaSpecificationExecutor<Handicap>{

}
