package com.uds.horbac.core.dao.emp_personalInfo;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import com.uds.horbac.core.entities.emp_personalInfo.Religion;

import io.swagger.annotations.Api;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Api(tags = "Religion Entity")
@RepositoryRestResource(path = "religions", exported = true)
public interface ReligionRepository extends JpaRepository<Religion, Long>, JpaSpecificationExecutor<Religion>{

}
