package com.uds.horbac.core.dao.emp_personalInfo;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import com.uds.horbac.core.entities.emp_personalInfo.SpecialIdentity;

import io.swagger.annotations.Api;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Api(tags = "SpecialIdentity Entity")
@RepositoryRestResource(path = "special-identities", exported = true)
public interface SpecialIdentityRepository extends JpaRepository<SpecialIdentity, String>{

}
