package com.uds.horbac.core.service.requests;

import com.uds.horbac.core.dao.requests.RequestRepository;
import com.uds.horbac.core.entities.requests.Request;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class RequestService {

	private RequestRepository requestRepository;

	@Autowired
	public RequestService(RequestRepository requestRepository) {
		this.requestRepository = requestRepository;
	}

}
