package com.uds.horbac.core.dao.contexts;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import com.uds.horbac.core.entities.activities.Action;
import com.uds.horbac.core.entities.contexts.Define;
import com.uds.horbac.core.entities.employees.Approver;
import com.uds.horbac.core.entities.employees.Emitter;
import com.uds.horbac.core.entities.organizations.Organization;
import com.uds.horbac.core.entities.resources.Resource;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Repository
public interface DefineRepository extends JpaRepository<Define, Long>, JpaSpecificationExecutor<Define>{

	Define findAllByOrganizationAndEmployeeAndActionAndResource(Organization org, Approver approver, Action action,
			Resource resource);

	Define findAllByOrganizationAndEmployeeAndActionAndResource(Organization org, Emitter emitter, Action action,
			Resource resource);


}
