package com.uds.horbac.core.dao.contexts;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import com.uds.horbac.core.entities.contexts.HOLocation;

import io.swagger.annotations.Api;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Api(tags = "Location Entity")
@RepositoryRestResource(path = "locations", exported = true)
public interface LocationRepository extends JpaRepository<HOLocation, Long>, JpaSpecificationExecutor<HOLocation>{

}
