package com.uds.horbac.core.service.employees;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.uds.horbac.core.dao.employees.ApproverRepository;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class ApproverService {

	private ApproverRepository approverRepository;

	@Autowired
	public ApproverService(ApproverRepository approverRepository) {
		this.approverRepository = approverRepository;
	}

}
