package com.uds.horbac.core.service.employees;

import com.uds.horbac.core.dao.employees.EmitterRepository;
import com.uds.horbac.core.entities.employees.Emitter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class EmitterService {

	private EmitterRepository emitterRepository;

	@Autowired
	public EmitterService(EmitterRepository emitterRepository) {
		this.emitterRepository = emitterRepository;
	}

}
