package com.uds.horbac.core.service.employees;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.uds.horbac.core.dao.employees.EmployeeRepository;
import com.uds.horbac.core.entities.employees.Employee;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class EmployeeService {
	
	@Autowired
	private EmployeeRepository employeeRepository;

	public List<Employee> getAll() {
		return employeeRepository.findAll();
	}

	public Employee getEmployee(Long id) {
		return employeeRepository.getOne(id);
	}

	public Employee save(Employee emp) {
		return employeeRepository.save(emp);
	}

	public void delete(Long id) {
		employeeRepository.deleteById(id);
	}

}
