package com.uds.horbac.core.service.employees;

import com.uds.horbac.core.dao.employees.EmploysRepository;
import com.uds.horbac.core.entities.employees.Employs;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class EmploysService {

	private EmploysRepository employsRepository;

	@Autowired
	public EmploysService(EmploysRepository employsRepository) {
		this.employsRepository = employsRepository;
	}

}
