package com.uds.horbac.core.dao.emp_healthInfo;

import com.uds.horbac.core.entities.emp_healthInfo.Medecin;
import io.swagger.annotations.Api;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

/**
 * Generated by Spring Data Generator on 31/12/2020
 */
@Api(tags = "Medecin Entity")
@RepositoryRestResource(path = "medecins", exported = true)
public interface MedecinRepository extends JpaRepository<Medecin, Long> {

}
