package com.uds.horbac.core.dao.emp_healthInfo;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import com.uds.horbac.core.entities.emp_healthInfo.Pharmacy;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Repository
public interface PharmacyRepository extends JpaRepository<Pharmacy, Long>, JpaSpecificationExecutor<Pharmacy>{

}
