package com.uds.horbac.core.dao.emp_healthInfo;

import com.uds.horbac.core.entities.emp_healthInfo.Pharmacy;
import io.swagger.annotations.Api;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

/**
 * Generated by Spring Data Generator on 31/12/2020
 */
@Api(tags = "Pharmacy Entity")
@RepositoryRestResource(path = "pharmacies", exported = true)
public interface PharmacyRepository extends JpaRepository<Pharmacy, Long>, JpaSpecificationExecutor<Pharmacy> {

}
