package com.uds.horbac.core.dao.units;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.http.MediaType;
import com.uds.horbac.core.entities.units.AdministrativeUnit;
import io.swagger.annotations.Api;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Api(tags = "AdministrativeUnit Controller", produces = MediaType.APPLICATION_JSON_VALUE)
@RepositoryRestResource(path = "admin-units", exported = true)
public interface AdministrativeUnitRepository extends JpaRepository<AdministrativeUnit, Long>, JpaSpecificationExecutor<AdministrativeUnit> {
}
