package com.uds.horbac.core.dao.units;

import com.uds.horbac.core.entities.units.OperationalUnit;
import io.swagger.annotations.Api;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.Optional;

/**
 * Generated by Spring Data Generator on 31/12/2020
 */
@Api(tags = "OperationalUnit Entity")
@RepositoryRestResource(path = "operational-units", exported = true)
@CrossOrigin(methods = {RequestMethod.GET, RequestMethod.POST, RequestMethod.DELETE, RequestMethod.PUT, RequestMethod.PATCH},
        maxAge = 3600)
public interface OperationalUnitRepository extends JpaRepository<OperationalUnit, Long>, JpaSpecificationExecutor<OperationalUnit> {
    Optional<OperationalUnit> findFirstByKey(String key);
}
