package com.uds.horbac.core.dao.units;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import com.uds.horbac.core.entities.units.OrgUnit;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Repository
public interface OrgUnitRepository extends JpaRepository<OrgUnit, Long>, JpaSpecificationExecutor<OrgUnit>{

}
