package com.uds.horbac.core.dao.units;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import com.uds.horbac.core.entities.units.PlaceUnder;

import io.swagger.annotations.Api;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Api(tags = "PlaceUnder Entity")
@RepositoryRestResource(path = "place-unders", exported = true)
public interface PlaceUnderRepository extends JpaRepository<PlaceUnder, Long>, JpaSpecificationExecutor<PlaceUnder>{

}
