package com.uds.horbac.core.dao.units;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import com.uds.horbac.core.entities.organizations.Organization;
import com.uds.horbac.core.entities.units.AdministrativeUnit;
import com.uds.horbac.core.entities.units.OperationalUnit;
import com.uds.horbac.core.entities.units.PlaceUnder;

/**
* Generated by Spring Data Generator on 31/12/2020
**/
@Repository
public interface PlaceUnderRepository extends JpaRepository<PlaceUnder, Long>, JpaSpecificationExecutor<PlaceUnder>{
	
	List<PlaceUnder> findByOrganizationId(Long id);

	PlaceUnder findAllByOrganizationAndSuperiorAndSubordinate(Organization org, AdministrativeUnit au,
			OperationalUnit ou);

}
