package com.uds.horbac.core.dao.units;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import com.uds.horbac.core.entities.units.Subordinate;

import io.swagger.annotations.Api;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Api(tags = "Subordinate Entity")
@RepositoryRestResource(path = "subordinates", exported = true)
public interface SubordinateRepository extends JpaRepository<Subordinate, Long>, JpaSpecificationExecutor<Subordinate>{

}
