package com.uds.horbac.core.service.emp_healthInfo;

import com.uds.horbac.core.dao.emp_healthInfo.HospitalRepository;
import com.uds.horbac.core.entities.emp_healthInfo.Hospital;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class HospitalService {

	private HospitalRepository hospitalRepository;

	@Autowired
	public HospitalService(HospitalRepository hospitalRepository) {
		this.hospitalRepository = hospitalRepository;
	}

}
