package com.uds.horbac.core.service.emp_healthInfo;

import com.uds.horbac.core.dao.emp_healthInfo.MedecinRepository;
import com.uds.horbac.core.entities.emp_healthInfo.Medecin;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class MedecinService {

	private MedecinRepository medecinRepository;

	@Autowired
	public MedecinService(MedecinRepository medecinRepository) {
		this.medecinRepository = medecinRepository;
	}

}
