package com.uds.horbac.core.service.emp_healthInfo;

import com.uds.horbac.core.dao.emp_healthInfo.MedecinSpecialityRepository;
import com.uds.horbac.core.entities.emp_healthInfo.MedecinSpeciality;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class MedecinSpecialityService {

	private MedecinSpecialityRepository medecinSpecialityRepository;

	@Autowired
	public MedecinSpecialityService(MedecinSpecialityRepository medecinSpecialityRepository) {
		this.medecinSpecialityRepository = medecinSpecialityRepository;
	}

}
