package com.uds.horbac.core.service.providers;

import com.uds.horbac.core.dao.providers.IdentityProviderRepository;
import com.uds.horbac.core.entities.providers.IdentityProvider;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class IdentityProviderService {

	private IdentityProviderRepository identityProviderRepository;

	@Autowired
	public IdentityProviderService(IdentityProviderRepository identityProviderRepository) {
		this.identityProviderRepository = identityProviderRepository;
	}

}
