package com.uds.horbac.core.dao.emp_justiceInfo;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import com.uds.horbac.core.entities.emp_justiceInfo.LitigationJustice;

import io.swagger.annotations.Api;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Api(tags = "LitigationJustice Entity")
@RepositoryRestResource(path = "litigationJustices", exported = true)
public interface LitigationJusticeRepository extends JpaRepository<LitigationJustice, Long>, JpaSpecificationExecutor<LitigationJustice> {

}
