package com.uds.horbac.core.service.units;

import com.uds.horbac.core.dao.organizations.OrganizationRepository;
import com.uds.horbac.core.dao.units.AdministrativeUnitRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * Generated by Spring Data Generator on 31/12/2020
 */
@Service
public class AdministrativeUnitService {
    private final OrganizationRepository organizationRepository;

    @Autowired
    public AdministrativeUnitService(OrganizationRepository organizationRepository,
                                     AdministrativeUnitRepository administrativeUnitRepository) {
        this.organizationRepository = organizationRepository;
    }


}
