package com.uds.horbac.core.service.units;

import com.uds.horbac.core.dao.units.AdministrativeUnitRepository;
import com.uds.horbac.core.entities.units.AdministrativeUnit;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class AdministrativeUnitService {

	private AdministrativeUnitRepository administrativeUnitRepository;

	@Autowired
	public AdministrativeUnitService(AdministrativeUnitRepository administrativeUnitRepository) {
		this.administrativeUnitRepository = administrativeUnitRepository;
	}

}
