package com.uds.horbac.core.service.units;

import com.uds.horbac.core.dao.units.OperationalUnitRepository;
import com.uds.horbac.core.entities.units.OperationalUnit;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class OperationalUnitService {

	private OperationalUnitRepository operationalUnitRepository;

	@Autowired
	public OperationalUnitService(OperationalUnitRepository operationalUnitRepository) {
		this.operationalUnitRepository = operationalUnitRepository;
	}

}
