package com.uds.horbac.core.service.units;

import com.uds.horbac.core.dao.units.OrgUnitRepository;
import com.uds.horbac.core.entities.units.OrgUnit;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class OrgUnitService {

	private OrgUnitRepository orgUnitRepository;

	@Autowired
	public OrgUnitService(OrgUnitRepository orgUnitRepository) {
		this.orgUnitRepository = orgUnitRepository;
	}

}
