package com.uds.horbac.core.service.units;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.uds.horbac.core.dao.units.PlaceUnderRepository;
import com.uds.horbac.core.entities.units.PlaceUnder;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class PlaceUnderService {
	
	@Autowired
	private PlaceUnderRepository placeUnderRepository;
	
	public List<PlaceUnder> getAll() {
		return placeUnderRepository.findAll();
	}

	public PlaceUnder getPlaceUnder(Long id) {
		return placeUnderRepository.findById(id).orElse(null);
	}

	public PlaceUnder save(PlaceUnder rs) {
		return placeUnderRepository.save(rs);
	}

	public void delete(Long id) {
		placeUnderRepository.deleteById(id);		
	}

}
