package com.uds.horbac.core.service.units;

import com.uds.horbac.core.dao.units.PlaceUnderRepository;
import com.uds.horbac.core.entities.units.PlaceUnder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class PlaceUnderService {

	private PlaceUnderRepository placeUnderRepository;

	@Autowired
	public PlaceUnderService(PlaceUnderRepository placeUnderRepository) {
		this.placeUnderRepository = placeUnderRepository;
	}

}
