package com.uds.horbac.core.service.units;

import com.uds.horbac.core.dao.units.SubordinateRepository;
import com.uds.horbac.core.entities.units.Subordinate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class SubordinateService {

	private SubordinateRepository subordinateRepository;

	@Autowired
	public SubordinateService(SubordinateRepository subordinateRepository) {
		this.subordinateRepository = subordinateRepository;
	}

}
