package com.uds.horbac.core.dao.permissions;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import com.uds.horbac.core.entities.permissions.AdministrativePermission;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Repository
public interface AdministrativePermissionRepository extends JpaRepository<AdministrativePermission, Long>, JpaSpecificationExecutor<AdministrativePermission> {

}
