package com.uds.horbac.core.dao.permissions;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import com.uds.horbac.core.entities.permissions.AuthGrant;

import io.swagger.annotations.Api;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Api(tags = "AuthGrant Entity")
@RepositoryRestResource(path = "authGrants", exported = true)
public interface AuthGrantRepository extends JpaRepository<AuthGrant, Long>, JpaSpecificationExecutor<AuthGrant>{

}
