package com.uds.horbac.core.dao.permissions;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import com.uds.horbac.core.entities.permissions.OperationalPermission;

import io.swagger.annotations.Api;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Api(tags = "OperationalPermission Entity")
@RepositoryRestResource(path = "operational-permissions", exported = true)
public interface OperationalPermissionRepository extends JpaRepository<OperationalPermission, Long>, JpaSpecificationExecutor<OperationalPermission>{

}
