package com.uds.horbac.core.service.emp_educationInfo;

import com.uds.horbac.core.dao.emp_educationInfo.AwardRepository;
import com.uds.horbac.core.entities.emp_educationInfo.Award;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class AwardService {

	private AwardRepository awardRepository;

	@Autowired
	public AwardService(AwardRepository awardRepository) {
		this.awardRepository = awardRepository;
	}

}
