package com.uds.horbac.core.service.emp_educationInfo;

import com.uds.horbac.core.dao.emp_educationInfo.SchoolRepository;
import com.uds.horbac.core.entities.emp_educationInfo.School;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class SchoolService {

	private SchoolRepository schoolRepository;

	@Autowired
	public SchoolService(SchoolRepository schoolRepository) {
		this.schoolRepository = schoolRepository;
	}

}
