package com.uds.horbac.core.service.emp_workInfo;

import com.uds.horbac.core.dao.emp_workInfo.CompanyRepository;
import com.uds.horbac.core.entities.emp_workInfo.Company;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class CompanyService {

	private CompanyRepository companyRepository;

	@Autowired
	public CompanyService(CompanyRepository companyRepository) {
		this.companyRepository = companyRepository;
	}

}
