package com.uds.horbac.core.service.emp_workInfo;

import com.uds.horbac.core.dao.emp_workInfo.OccupiedFunctionRepository;
import com.uds.horbac.core.entities.emp_workInfo.OccupiedFunction;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class OccupiedFunctionService {

	private OccupiedFunctionRepository occupiedFunctionRepository;

	@Autowired
	public OccupiedFunctionService(OccupiedFunctionRepository occupiedFunctionRepository) {
		this.occupiedFunctionRepository = occupiedFunctionRepository;
	}

}
