package com.uds.horbac.core.service.permissions;

import com.uds.horbac.core.dao.permissions.AdministrativePermissionRepository;
import com.uds.horbac.core.entities.permissions.AdministrativePermission;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class AdministrativePermissionService {

	private AdministrativePermissionRepository administrativePermissionRepository;

	@Autowired
	public AdministrativePermissionService(AdministrativePermissionRepository administrativePermissionRepository) {
		this.administrativePermissionRepository = administrativePermissionRepository;
	}

}
