package com.uds.horbac.core.service.permissions;

import com.uds.horbac.core.dao.permissions.AuthGrantRepository;
import com.uds.horbac.core.entities.permissions.AuthGrant;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class AuthGrantService {

	private AuthGrantRepository authGrantRepository;

	@Autowired
	public AuthGrantService(AuthGrantRepository authGrantRepository) {
		this.authGrantRepository = authGrantRepository;
	}

}
