package com.uds.horbac.core.service.permissions;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.uds.horbac.core.dao.permissions.OperationalPermissionRepository;
import com.uds.horbac.core.entities.permissions.OperationalPermission;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class OperationalPermissionService {
	
	@Autowired
	private OperationalPermissionRepository apRepository;
	
	public List<OperationalPermission> getAll() {
		return apRepository.findAll();
	}

	public void delete(Long id) {
		apRepository.deleteById(id);		
	}

	public OperationalPermission save(OperationalPermission aop) {
		return apRepository.save(aop);
	}

	public OperationalPermission getOperationalPermission(Long id) {
		return apRepository.findById(id).orElse(null);
	}

}
