package com.uds.horbac.core.service.permissions;

import com.uds.horbac.core.dao.permissions.OperationalPermissionRepository;
import com.uds.horbac.core.entities.permissions.OperationalPermission;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class OperationalPermissionService {

	private OperationalPermissionRepository operationalPermissionRepository;

	@Autowired
	public OperationalPermissionService(OperationalPermissionRepository operationalPermissionRepository) {
		this.operationalPermissionRepository = operationalPermissionRepository;
	}

}
