package com.uds.horbac.core.dao.emp_educationInfo;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import com.uds.horbac.core.entities.emp_educationInfo.Diploma;

import io.swagger.annotations.Api;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Api(tags = "Diploma Entity")
@RepositoryRestResource(path = "diplomas", exported = true)
public interface DiplomaRepository extends JpaRepository<Diploma, Long>, JpaSpecificationExecutor<Diploma>{

}
