package com.uds.horbac.core.dao.providers;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import com.uds.horbac.core.entities.providers.IdentityProvider;

import io.swagger.annotations.Api;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Api(tags = "Identity provider Entity")
@RepositoryRestResource(path = "identity-providers", exported = true)
public interface IdentityProviderRepository extends JpaRepository<IdentityProvider, Long>, JpaSpecificationExecutor<IdentityProvider> {

}
