package com.uds.horbac.core.dao.emp_passionInfo;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import com.uds.horbac.core.entities.emp_passionInfo.HairdressingSalon;

import io.swagger.annotations.Api;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Api(tags = "HairdressingSalon Entity")
@RepositoryRestResource(path = "hairdressingSalons", exported = true)
public interface HairdressingSalonRepository extends JpaRepository<HairdressingSalon, Long>, JpaSpecificationExecutor<HairdressingSalon>{

}
