package com.uds.horbac.core.dao.emp_passionInfo;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import com.uds.horbac.core.entities.emp_passionInfo.HairdressingSalon;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Repository
public interface HairdressingSalonRepository extends JpaRepository<HairdressingSalon, Long>, JpaSpecificationExecutor<HairdressingSalon>{

}
