package com.uds.horbac.core.dao.emp_passionInfo;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import com.uds.horbac.core.entities.emp_passionInfo.Supermarket;

import io.swagger.annotations.Api;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Api(tags = "Supermarket Entity")
@RepositoryRestResource(path = "supermarkets", exported = true)
public interface SupermarketRepository extends JpaRepository<Supermarket, Long>, JpaSpecificationExecutor<Supermarket>{

}
