package com.uds.horbac.core.rest.resources;

import java.util.List;
import java.util.stream.Collectors;

import org.modelmapper.ModelMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.uds.horbac.core.dto.resources.ScopeDTO;
import com.uds.horbac.core.service.resources.ScopeService;

/**
 * The default REST controller logic
 * <p>
 * This file has been automatically generated by Speedment. Any changes made to
 * it will be overwritten.
 * 
 * @author Fidèle
 */
@RestController
public class ScopeController {
    
	protected @Autowired ScopeService service;    
    protected @Autowired ModelMapper modelMapper;
    
    @GetMapping(value = "/scopes")
    public List<ScopeDTO> get(@RequestParam(value = "start", defaultValue = "0") long start, @RequestParam(value = "limit", defaultValue = "25") long limit) {
    	return service.getAll().stream()
				.map(clt -> modelMapper.map(clt, ScopeDTO.class))
				.collect(Collectors.toList());
    }
}