package com.uds.horbac.core.service.contexts;

import com.uds.horbac.core.dao.contexts.ContextRepository;
import com.uds.horbac.core.entities.contexts.Context;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class ContextService {

	private ContextRepository contextRepository;

	@Autowired
	public ContextService(ContextRepository contextRepository) {
		this.contextRepository = contextRepository;
	}

}
