package com.uds.horbac.core.service.contexts;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.uds.horbac.core.dao.contexts.ContextRepository;
import com.uds.horbac.core.entities.contexts.Context;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class ContextService {
	
	@Autowired
	private ContextRepository contextRepository;

	public List<Context> getAll() {
		return contextRepository.findAll();
	}

	public Context getContext(Long id) {
		return contextRepository.getOne(id);
	}

	public Context save(Context ctx) {
		return contextRepository.save(ctx);
	}

	public void delete(Long id) {
		contextRepository.deleteById(id);
	}

}
