package com.uds.horbac.core.service.contexts;

import com.uds.horbac.core.dao.contexts.DefineRepository;
import com.uds.horbac.core.entities.contexts.Define;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class DefineService {

	private DefineRepository defineRepository;

	@Autowired
	public DefineService(DefineRepository defineRepository) {
		this.defineRepository = defineRepository;
	}

}
