package com.uds.horbac.core.service.contexts;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.uds.horbac.core.dao.contexts.DefineRepository;
import com.uds.horbac.core.entities.contexts.Define;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class DefineService {
	
	@Autowired
	private DefineRepository defineRepository;

	public List<Define> getAll() {
		return defineRepository.findAll();
	}

	public Define getDefine(Long id) {
		return defineRepository.getOne(id);
	}

	public Object save(Define def) {
		return defineRepository.save(def);
	}

	public void delete(Long id) {
		defineRepository.deleteById(id);
	}

}
