package com.uds.horbac.core.service.contexts;

import com.uds.horbac.core.dao.contexts.LocationRepository;
import com.uds.horbac.core.entities.contexts.HOLocation;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class LocationService {

	private LocationRepository locationRepository;

	@Autowired
	public LocationService(LocationRepository locationRepository) {
		this.locationRepository = locationRepository;
	}

}
