package com.uds.horbac.core.service.emp_famillyInfo;

import com.uds.horbac.core.dao.emp_famillyInfo.PartenaireConjugalRepository;
import com.uds.horbac.core.entities.emp_famillyInfo.PartenaireConjugal;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class PartenaireConjugalService {

	private PartenaireConjugalRepository partenaireConjugalRepository;

	@Autowired
	public PartenaireConjugalService(PartenaireConjugalRepository partenaireConjugalRepository) {
		this.partenaireConjugalRepository = partenaireConjugalRepository;
	}

}
