package com.uds.horbac.core.dao.employees;

import com.uds.horbac.core.entities.employees.Employee;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
 * Generated by Spring Data Generator on 31/12/2020
 */
@Repository
public interface EmployeeRepository extends
        JpaRepository<Employee, Long>,
        JpaSpecificationExecutor<Employee> {

    Employee findByFirstName(String firstName);
}
