package com.uds.horbac.core.dao.clients;

import com.uds.horbac.core.entities.clients.Client;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Repository
public interface ClientRepository extends JpaRepository<Client, Long>{

}
