package com.uds.horbac.core.service.emp_passionInfo;

import com.uds.horbac.core.dao.emp_passionInfo.HairdressingSalonRepository;
import com.uds.horbac.core.entities.emp_passionInfo.HairdressingSalon;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class HairdressingSalonService {

	private HairdressingSalonRepository hairdressingSalonRepository;

	@Autowired
	public HairdressingSalonService(HairdressingSalonRepository hairdressingSalonRepository) {
		this.hairdressingSalonRepository = hairdressingSalonRepository;
	}

}
