package com.uds.horbac.core.service.emp_passionInfo;

import com.uds.horbac.core.dao.emp_passionInfo.HairStyleRepository;
import com.uds.horbac.core.entities.emp_passionInfo.HairStyle;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class HairStyleService {

	private HairStyleRepository hairStyleRepository;

	@Autowired
	public HairStyleService(HairStyleRepository hairStyleRepository) {
		this.hairStyleRepository = hairStyleRepository;
	}

}
