package com.uds.horbac.core.service.emp_passionInfo;

import com.uds.horbac.core.dao.emp_passionInfo.HobbyRepository;
import com.uds.horbac.core.entities.emp_passionInfo.Hobby;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class HobbyService {

	private HobbyRepository hobbyRepository;

	@Autowired
	public HobbyService(HobbyRepository hobbyRepository) {
		this.hobbyRepository = hobbyRepository;
	}

}
