package com.uds.horbac.core.service.emp_passionInfo;

import com.uds.horbac.core.dao.emp_passionInfo.SewingSalonRepository;
import com.uds.horbac.core.entities.emp_passionInfo.SewingSalon;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class SewingSalonService {

	private SewingSalonRepository sewingSalonRepository;

	@Autowired
	public SewingSalonService(SewingSalonRepository sewingSalonRepository) {
		this.sewingSalonRepository = sewingSalonRepository;
	}

}
