package com.uds.horbac.core.service.emp_passionInfo;

import com.uds.horbac.core.dao.emp_passionInfo.SupermarketRepository;
import com.uds.horbac.core.entities.emp_passionInfo.Supermarket;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class SupermarketService {

	private SupermarketRepository supermarketRepository;

	@Autowired
	public SupermarketService(SupermarketRepository supermarketRepository) {
		this.supermarketRepository = supermarketRepository;
	}

}
