package com.uds.horbac.core.service.emp_passionInfo;

import com.uds.horbac.core.dao.emp_passionInfo.VisitRepository;
import com.uds.horbac.core.entities.emp_passionInfo.Visit;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class VisitService {

	private VisitRepository visitRepository;

	@Autowired
	public VisitService(VisitRepository visitRepository) {
		this.visitRepository = visitRepository;
	}

}
