package com.uds.horbac.core.rest.users;

import java.util.List;
import java.util.stream.Collectors;

import javax.validation.Valid;

import org.modelmapper.ModelMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

import com.uds.horbac.core.dto.users.ExternalIdentityDTO;
import com.uds.horbac.core.entities.users.ExternalIdentity;
import com.uds.horbac.core.service.users.ExternalIdentityService;

/**
 * The default REST controller logic
 * <p>
 * This file has been automatically generated by Speedment. Any changes made to
 * it will be overwritten.
 * 
 * @author Fidele
 */
@RestController
public  class ExternalIdentityController {
    
	protected @Autowired ExternalIdentityService service;    
    protected @Autowired ModelMapper modelMapper;
    
    @GetMapping(value = "/externalId")
    public List<ExternalIdentityDTO> get(@RequestParam(value = "start", defaultValue = "0") long start, @RequestParam(value = "limit", defaultValue = "25") long limit) {
    	return service.getAll().stream()
				.map(clt -> modelMapper.map(clt, ExternalIdentityDTO.class))
				.collect(Collectors.toList());
    }
    
    @GetMapping("/externalId/{id}")
   	@ResponseStatus(value=HttpStatus.OK)
   	public ExternalIdentityDTO getExternelIdById(@PathVariable Long id){
   		return modelMapper.map(service.getExternalId(id), ExternalIdentityDTO.class);
   	}
   	
   	@PostMapping("/externalId")
   	@ResponseStatus(value=HttpStatus.CREATED)
   	public ExternalIdentityDTO createExternalId(@Valid @RequestBody ExternalIdentityDTO cltDTO){
   		ExternalIdentity clt = modelMapper.map(cltDTO, ExternalIdentity.class);
   		
   		return modelMapper.map(service.save(clt), ExternalIdentityDTO.class);
   	}
   	
   	@PutMapping("/externalId")
   	@ResponseStatus(value=HttpStatus.OK)
   	public ExternalIdentityDTO  updateExternalId(@Valid @RequestBody ExternalIdentityDTO cltDTO) {		
   		ExternalIdentity clt = modelMapper.map(cltDTO, ExternalIdentity.class);		
   		return modelMapper.map(service.save(clt), ExternalIdentityDTO.class);
   	}
   	
   	@DeleteMapping(value = "/externalId/{id}")
   	@ResponseStatus(value=HttpStatus.OK)
   	public void delete(@PathVariable Long id){
   		service.delete(id);
   	}
}