package com.uds.horbac.core.rest.users;

import java.util.List;
import java.util.stream.Collectors;

import org.modelmapper.ModelMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.uds.horbac.core.dto.clients.ClientDTO;
import com.uds.horbac.core.dto.users.ExternalIdentityDTO;
import com.uds.horbac.core.service.users.ExternalIdentityService;

/**
 * The default REST controller logic
 * <p>
 * This file has been automatically generated by Speedment. Any changes made to
 * it will be overwritten.
 * 
 * @author Fidèle
 */
@RestController
public  class ExternalIdentityController {
    
	protected @Autowired ExternalIdentityService service;    
    protected @Autowired ModelMapper modelMapper;
    
    @GetMapping(value = "/externalId")
    public List<ExternalIdentityDTO> get(@RequestParam(value = "start", defaultValue = "0") long start, @RequestParam(value = "limit", defaultValue = "25") long limit) {
    	return service.getAll().stream()
				.map(clt -> modelMapper.map(clt, ExternalIdentityDTO.class))
				.collect(Collectors.toList());
    }
}