package com.uds.horbac.core.rest.users;

import static org.springframework.web.bind.annotation.RequestMethod.GET;

import java.util.List;
import java.util.stream.Collectors;

import org.modelmapper.ModelMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.uds.horbac.core.dto.users.UserDTO;
import com.uds.horbac.core.service.users.UserService;

/**
 * The default REST controller logic
 * <p>
 * This file has been automatically generated by Speedment. Any changes made to
 * it will be overwritten.
 * 
 * @author Fidèle
 */
@RestController
public class UserController {
    
	protected @Autowired UserService service;    
    protected @Autowired ModelMapper modelMapper;
    
    @RequestMapping(value = "/users", method = GET)
    public List<UserDTO> get(@RequestParam(value = "start", defaultValue = "0") long start, @RequestParam(value = "limit", defaultValue = "25") long limit) {
    	return service.getAll().stream()
				.map(clt -> modelMapper.map(clt, UserDTO.class))
				.collect(Collectors.toList());
    }
}