package com.uds.horbac.core.dao.resources;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import com.uds.horbac.core.entities.resources.Scope;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Repository
public interface ScopeRepository extends JpaRepository<Scope, Long>, JpaSpecificationExecutor<Scope> {

}
