package com.uds.horbac.core.dao.resources;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import com.uds.horbac.core.entities.organizations.Organization;
import com.uds.horbac.core.entities.resources.Resource;
import com.uds.horbac.core.entities.resources.Uses;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Repository
public interface UsesRepository extends JpaRepository<Uses, Long>, JpaSpecificationExecutor<Uses> {

	Uses findAllByOrganizationAndResource(Organization org, Resource resource);

}
