package com.uds.horbac.core.dao.resources;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import com.uds.horbac.core.entities.resources.Vue;

import io.swagger.annotations.Api;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Api(tags = "Vue Entity")
@RepositoryRestResource(path = "views", exported = true)
public interface VueRepository extends JpaRepository<Vue, Long>, JpaSpecificationExecutor<Vue> {

}
