package com.uds.horbac.core.dao.emp_workInfo;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import com.uds.horbac.core.entities.emp_workInfo.OccupiedFunction;

import io.swagger.annotations.Api;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Api(tags = "OccupiedFunction Entity")
@RepositoryRestResource(path = "occupiedFunctions", exported = true)
public interface OccupiedFunctionRepository extends JpaRepository<OccupiedFunction, Long>, JpaSpecificationExecutor<OccupiedFunction>{

}
