package com.uds.horbac.core.service.emp_personalInfo;

import com.uds.horbac.core.dao.emp_personalInfo.AddressRepository;
import com.uds.horbac.core.entities.emp_personalInfo.Address;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class AddressService {

	private AddressRepository addressRepository;

	@Autowired
	public AddressService(AddressRepository addressRepository) {
		this.addressRepository = addressRepository;
	}

}
