package com.uds.horbac.core.service.emp_personalInfo;

import com.uds.horbac.core.dao.emp_personalInfo.CityRepository;
import com.uds.horbac.core.entities.emp_personalInfo.City;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class CityService {

	private CityRepository cityRepository;

	@Autowired
	public CityService(CityRepository cityRepository) {
		this.cityRepository = cityRepository;
	}

}
