package com.uds.horbac.core.service.emp_personalInfo;

import com.uds.horbac.core.dao.emp_personalInfo.HandicapTypeRepository;
import com.uds.horbac.core.entities.emp_personalInfo.HandicapType;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class HandicapTypeService {

	private HandicapTypeRepository handicapTypeRepository;

	@Autowired
	public HandicapTypeService(HandicapTypeRepository handicapTypeRepository) {
		this.handicapTypeRepository = handicapTypeRepository;
	}

}
