package com.uds.horbac.core.service.emp_personalInfo;

import com.uds.horbac.core.dao.emp_personalInfo.PersonRepository;
import com.uds.horbac.core.entities.emp_personalInfo.Person;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class PersonService {

	private PersonRepository personRepository;

	@Autowired
	public PersonService(PersonRepository personRepository) {
		this.personRepository = personRepository;
	}

}
