package com.uds.horbac.core.service.emp_personalInfo;

import com.uds.horbac.core.dao.emp_personalInfo.PhoneOperatorRepository;
import com.uds.horbac.core.entities.emp_personalInfo.PhoneOperator;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class PhoneOperatorService {

	private PhoneOperatorRepository phoneOperatorRepository;

	@Autowired
	public PhoneOperatorService(PhoneOperatorRepository phoneOperatorRepository) {
		this.phoneOperatorRepository = phoneOperatorRepository;
	}

}
