package com.uds.horbac.core.service.emp_personalInfo;

import com.uds.horbac.core.dao.emp_personalInfo.PhoneNumberRepository;
import com.uds.horbac.core.entities.emp_personalInfo.PhoneNumber;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class PhoneNumberService {

	private PhoneNumberRepository phoneNumberRepository;

	@Autowired
	public PhoneNumberService(PhoneNumberRepository phoneNumberRepository) {
		this.phoneNumberRepository = phoneNumberRepository;
	}

}
