package com.uds.horbac.core.service.emp_personalInfo;

import com.uds.horbac.core.dao.emp_personalInfo.ReligionRepository;
import com.uds.horbac.core.entities.emp_personalInfo.Religion;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class ReligionService {

	private ReligionRepository religionRepository;

	@Autowired
	public ReligionService(ReligionRepository religionRepository) {
		this.religionRepository = religionRepository;
	}

}
