package com.uds.horbac.core.service.emp_ownershipInfo;

import com.uds.horbac.core.dao.emp_ownershipInfo.BiensImmobiliersRepository;
import com.uds.horbac.core.entities.emp_ownershipInfo.BiensImmobiliers;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class BiensImmobiliersService {

	private BiensImmobiliersRepository biensImmobiliersRepository;

	@Autowired
	public BiensImmobiliersService(BiensImmobiliersRepository biensImmobiliersRepository) {
		this.biensImmobiliersRepository = biensImmobiliersRepository;
	}

}
