package com.uds.horbac.core.service.emp_ownershipInfo;

import com.uds.horbac.core.dao.emp_ownershipInfo.CarrosserieRepository;
import com.uds.horbac.core.entities.emp_ownershipInfo.Carrosserie;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class CarrosserieService {

	private CarrosserieRepository carrosserieRepository;

	@Autowired
	public CarrosserieService(CarrosserieRepository carrosserieRepository) {
		this.carrosserieRepository = carrosserieRepository;
	}

}
