package com.uds.horbac.core.service.emp_ownershipInfo;

import com.uds.horbac.core.dao.emp_ownershipInfo.DeviceTypeRepository;
import com.uds.horbac.core.entities.emp_ownershipInfo.DeviceType;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class DeviceTypeService {

	private DeviceTypeRepository deviceTypeRepository;

	@Autowired
	public DeviceTypeService(DeviceTypeRepository deviceTypeRepository) {
		this.deviceTypeRepository = deviceTypeRepository;
	}

}
