package com.uds.horbac.core.service.emp_ownershipInfo;

import com.uds.horbac.core.dao.emp_ownershipInfo.VehicleRepository;
import com.uds.horbac.core.entities.emp_ownershipInfo.Vehicle;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class VehicleService {

	private VehicleRepository vehicleRepository;

	@Autowired
	public VehicleService(VehicleRepository vehicleRepository) {
		this.vehicleRepository = vehicleRepository;
	}

}
