package com.uds.horbac.core.service.emp_ownershipInfo;

import com.uds.horbac.core.dao.emp_ownershipInfo.VehiculeTypeRepository;
import com.uds.horbac.core.entities.emp_ownershipInfo.VehiculeType;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class VehiculeTypeService {

	private VehiculeTypeRepository vehiculeTypeRepository;

	@Autowired
	public VehiculeTypeService(VehiculeTypeRepository vehiculeTypeRepository) {
		this.vehiculeTypeRepository = vehiculeTypeRepository;
	}

}
