package com.uds.horbac.core.service.emp_ownershipInfo;

import com.uds.horbac.core.dao.emp_ownershipInfo.WheelRepository;
import com.uds.horbac.core.entities.emp_ownershipInfo.Wheel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class WheelService {

	private WheelRepository wheelRepository;

	@Autowired
	public WheelService(WheelRepository wheelRepository) {
		this.wheelRepository = wheelRepository;
	}

}
