package com.uds.horbac.core.service.emp_justiceInfo;

import com.uds.horbac.core.dao.emp_justiceInfo.LitigationJusticeRepository;
import com.uds.horbac.core.entities.emp_justiceInfo.LitigationJustice;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class LitigationJusticeService {

	private LitigationJusticeRepository litigationJusticeRepository;

	@Autowired
	public LitigationJusticeService(LitigationJusticeRepository litigationJusticeRepository) {
		this.litigationJusticeRepository = litigationJusticeRepository;
	}

}
