package com.uds.horbac.core.service.clients;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.uds.horbac.core.dao.clients.ClientTypeRepository;
import com.uds.horbac.core.entities.clients.ClientType;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class ClientTypeService {
	@Autowired
	private ClientTypeRepository clientTypeRepository;

	public List<ClientType> getAll() {
		return clientTypeRepository.findAll();
	}

}
