package com.uds.horbac.core.service.clients;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.uds.horbac.core.dao.clients.ClientRepository;
import com.uds.horbac.core.entities.clients.Client;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class ClientService {
	
	@Autowired
	private ClientRepository clientRepository;

	public List<Client> getAll() {
		// TODO Auto-generated method stubs
		return clientRepository.findAll();
	}

	public void delete(Long id) {
		clientRepository.deleteById(id);		
	}

	public Client save(Client clt) {
		return clientRepository.save(clt);
	}

	public Client getClient(Long id) {
		return clientRepository.findById(id).orElse(null);
	}

}
