package com.uds.horbac.core.service.users;

import java.util.Collection;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.uds.horbac.core.dao.users.ExternalIdentityRepository;
import com.uds.horbac.core.entities.users.ExternalIdentity;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class ExternalIdentityService {
	
	@Autowired
	private ExternalIdentityRepository externalIdentityRepository;

	public Collection<ExternalIdentity> getAll() {
		return externalIdentityRepository.findAll();
	}

}
