package com.uds.horbac.core.service.resources;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.uds.horbac.core.dao.resources.ResourceRepository;
import com.uds.horbac.core.entities.resources.Resource;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class ResourceService {
	@Autowired
	private ResourceRepository resourceRepository;

	public List<Resource> getAll() {
		return resourceRepository.findAll();
	}

	public Resource getResource(Long id) {
		return resourceRepository.findById(id).orElse(null);
	}

	public Resource save(Resource rs) {
		return resourceRepository.save(rs);
	}

	public void delete(Long id) {
		resourceRepository.deleteById(id);		
	}

}
