package com.uds.horbac.core.service.resources;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.uds.horbac.core.dao.resources.ScopeRepository;
import com.uds.horbac.core.entities.resources.Scope;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class ScopeService {
	@Autowired
	private ScopeRepository scopeRepository;

	public List<Scope> getAll() {
		return scopeRepository.findAll();
	}

}
