package com.uds.horbac.core.service.resources;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.uds.horbac.core.dao.resources.UsesRepository;
import com.uds.horbac.core.entities.resources.Uses;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class UsesService {
	@Autowired
	private UsesRepository usesRepository;

	public List<Uses> getAll() {
		return usesRepository.findAll();
	}

}
