package com.uds.horbac.core.service.resources;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.uds.horbac.core.dao.resources.VueRepository;
import com.uds.horbac.core.entities.resources.Vue;

/**
* Generated by Spring Data Generator on 31/12/2020
*/
@Component
public class VueService {
	
	@Autowired
	private VueRepository vueRepository;


	public List<Vue> getAll() {
		return vueRepository.findAll();
	}

}
