package com.uds.horbac.core.dao.users;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.uds.horbac.core.entities.employees.Employee;
import com.uds.horbac.core.entities.users.User;

/**
 * Generated by Spring Data Generator on 31/12/2020
 */
@Repository
public interface UserRepository extends JpaRepository<User, Long>, JpaSpecificationExecutor<User> {

    boolean existsByUsername(String username);

    Optional<User> findByUsername(String username);

    @Query(value = "SELECT u FROM User u WHERE u.username LIKE %?1%")
    List<User> filterUsers(String query);

    @Query("SELECT COUNT(e) FROM User e")
    long countAll();

    Optional<User> findByEmployee(Employee employee);

    User findByEmployeeId(Long id);

    @Query("SELECT u FROM User u " +
            "INNER JOIN Employee e ON u.employee.id = e.id " +
            "INNER JOIN Appoints eu ON e.id = eu.employee.id " +
            "INNER JOIN OrgUnit un ON eu.adminUnit.id = un.id " +
            "WHERE un.id IN :unitIds")
    List<User> findUsersByAdminUnitIds(@Param("unitIds") List<Long> unitIds);
}
